gateway:
  build: MedBook-Gateway
  container_name: "gateway"
  ports:
   - "8000:10000"
  volumes:
   - ./MedBook-Gateway:/app-dev
  command: /app-dev/runDev.sh

telescope:
  container_name: "telescope"
  build: MedBook-Telescope3
  volumes:
  - ./MedBook-Telescope3:/app-dev
  command: /app-dev/dockerDev.sh

# some probem loading fs-extra
# fusion:
#   build: MedBook-Fusion5
#   volumes:
#   - ./MedBook-Fusion5/webapp:/app-dev
#   command: /app-dev/dockerDev.sh
#   links:
#   - mongo
# 

crfs:
  build: MedBook-CRFS
  container_name: "crfs"
  volumes:
  - ./MedBook-CRFS/webapp:/app-dev
  command: /app-dev/dockerDev.sh
  environment:
    ROOT_URL: ${ROOT_URL}/CRF


##TODO should probably pin down the version of Mongo
mongo:
  container_name: "mongo"
  image: mongo

  # uncomment when you want to talk directly to moongo
  # from outside a container
  # ports:
  #   - "127.0.0.1:27017:27017"
