#ansible-playbook playbook.yml -i hosts -u root
---

# - hosts: all
#   tasks:
#     - name: Update packages
#       apt: update_cache=yes
#       become: yes
#       become_method: sudo

- hosts: docker
  tasks:
    #BEGIN AZURE SPECIFIC CODE
    #Really all this is just to get a disk with enough space attached
    #and used by Docker

    - name: Create filesystem on attached data disk
      filesystem: fstype=ext4 dev=/dev/sdc
      become: yes
      become_method: sudo

    - name: Point docker to bigger volume
      mount:
        name: /var/lib/docker
        src: /dev/sdc
        fstype: ext4
        state: mounted
      become: yes
      become_method: sudo

    #END AZURE SPECIFIC CODE

    - name: Install curl
      apt: pkg=curl
      become: yes
      become_method: sudo

    # Install Docker Engine
    - name: Add Docker repository key
      apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
      become: yes
      become_method: sudo

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
        update_cache: yes
      become: yes
      become_method: sudo

    - name: Install docker
      apt: pkg=docker-engine #TODO figure out how to pin this to a specific version
      become: yes
      become_method: sudo

    - name: Install docker-compose
      get_url:
        dest: /usr/local/bin/docker-compose
        url: https://github.com/docker/compose/releases/download/1.7.0/docker-compose-Linux-x86_64
        mode: 0755
      become: yes
      become_method: sudo

    - name: Add ubuntu user to docker group #allow ubuntu to run docker commands
      user: name=ubuntu group=docker
      become: yes
      become_method: sudo

- hosts: dev
  tasks:
    - name: Customize .bashrc
      template: src=templates/bashrc.j2 dest=~/.bashrc

    - name: Install emacs
      apt: pkg=emacs24-nox
      become: yes
      become_method: sudo

    - name: Install htop
      apt: pkg=htop
      become: yes
      become_method: sudo

    # possible to supress this waring?
    # [WARNING]: Consider using git module rather than running git
    # or perhaps there is a better way to do this
    # doesn't seem like the git module supports it though
    # http://docs.ansible.com/ansible/git_module.html
    - name: Configure git user
      shell: git config --global user.name {{git_name}}

    - name: Configure git email
      shell: git config --global user.email {{git_email}}

    - name: Set push default to simple
      shell: git config --global push.default simple
