#ansible-playbook playbook.yml -i hosts -u root
---

# - hosts: all
#   tasks:
#     - name: Update packages
#       apt: update_cache=yes
#       become: yes
#       become_method: sudo

- hosts: docker
  tasks:
    - name: Point docker to bigger volume #Probably not necessary with non-Azure cloud providers
      mount:
        name: /var/lib/docker
        src: /dev/sdc
        fstype: ext4
        state: mounted
      become: yes
      become_method: sudo

    - name: Install curl
      apt: pkg=curl
      become: yes
      become_method: sudo

    # Install Docker Engine
    - name: Add Docker repository key
      apt_key: keyserver=p80.pool.sks-keyservers.net id=58118E89F3A912897C070ADBF76221572C52609D
      become: yes
      become_method: sudo

    - name: Add Docker Repository
      apt_repository:
        repo: 'deb https://apt.dockerproject.org/repo ubuntu-xenial main'
        update_cache: yes
      become: yes
      become_method: sudo

    - name: Install docker
      apt: pkg=docker-engine #TODO figure out how to pin this to a specific version
      become: yes
      become_method: sudo

    - name: Install docker-compose
      get_url:
        dest: /usr/local/bin/docker-compose
        url: https://github.com/docker/compose/releases/download/1.7.0/docker-compose-Linux-x86_64
        mode: 755

    - name: Add ubuntu user to docker group #allow ubuntu to run docker commands
      user: name=ubuntu group=docker
      become: yes
      become_method: sudo

- hosts: dev
  tasks:
    - name: Customize .bashrc
      template: src=templates/bashrc.j2 dest=~/.bashrc

    - name: Install emacs
      apt: pkg=emacs24-nox
      become: yes
      become_method: sudo

    - name: Install htop
      apt: pkg=htop
      become: yes
      become_method: sudo
